const CDCATEGORIAENUM = {
    TABELA: 'CDCATEGORIA',
    CDCATID: 'CDCATID',
    CDCATNOME: 'CDCATNOME',
    CDCATEMPRESAID: 'CDCATEMPRESAID'
};

Object.freeze(CDCATEGORIAENUM);

export default CDCATEGORIAENUM;
