const CDEXCECAOENUM = {
    TABELA: 'CDEXCECAO',
    CDEXDESCRICAO: 'CDEXDESCRICAO',
    CDEXDATA: 'CDEXDATA',
    CDEXEMPRESAID: 'CDEXEMPRESAID',
};

Object.freeze(CDEXCECAOENUM);

export default CDEXCECAOENUM;