const CDPRODUTOENUM = {
    TABELA: 'CDPRODUTO',
    CDPRODID: 'CDPRODID',
    CDPRODNOME: 'CDPRODNOME',
    CDPRODDESCRICAO: 'CDPRODDESCRICAO',
    CDPRODPRECOREAL: 'CDPRODPRECOREAL',
    CDPRODPRECOPONTO: 'CDPRODPRECOPONTO',
    CDPRODPRECODESCONTO: 'CDPRODPRECODESCONTO',
    CDPRODQTDESTOQUE: 'CDPRODQTDESTOQUE',
    CDPRODEMPRESAID: 'CDPRODEMPRESAID',
    CDPRODCATEGORIAID: 'CDPRODCATEGORIAID',
};

Object.freeze(CDPRODUTOENUM);

export default CDPRODUTOENUM;