const CDPRODUTOIMAGEMENUM = {
    TABELA: 'CDPRODUTOIMAGEM',
    CDPRODIMGID: 'CDPRODIMGID',
    CDPRODIMGBLOB: 'CDPRODIMGBLOB',
    CDPRODIMGPRODUTOID: 'CDPRODIMGPRODUTOID',
    CDPRODIMGORDEM: 'CDPRODIMGORDEM',
};

Object.freeze(CDPRODUTOIMAGEMENUM);

export default CDPRODUTOIMAGEMENUM;