const CDPRIVILEGIOENUM = {
    TABELA: 'CDPRIVILEGIO',
    CDPRIVID: 'CDPRIVID',
    CDPRIVCHAVE: 'CDPRIVCHAVE',
    CDPRIVNOME: 'CDPRIVNOME',
    CDPRIVMODULO: 'CDPRIVMODULO'
};

Object.freeze(CDPRIVILEGIOENUM);

export default CDPRIVILEGIOENUM;
