const CDSENHAENUM = {
    TABELA: 'CDSENHA',
    CDSEID: 'CDSEID',
    CDSENOME: 'CDSENOME',
    CDSECPFCNPJ: 'CDSECPFCNPJ',
    CDSEEMAIL: 'CDSEEMAIL',
    CDSETELEFONE: 'CDSETELEFONE',
    CDSECARGOID: 'CDSECARGOID',
};

Object.freeze(CDSENHAENUM);

export default CDSENHAENUM;