const LCAUDITORIAENUM = {
    TABELA: 'LCAUDITORIA',
    LCAUDID: 'LCAUDID',
    LCAUDDESCRICAO: 'LCAUDDESCRICAO',
    LCAUDDATA: 'LCAUDDATA',
    LCAUDACAOID: 'LCAUDACAOID',
    LCAUDEMPRESAID: 'LCAUDEMPRESAID',
    LCAUDSENHAID: 'LCAUDSENHAID',
};

Object.freeze(LCAUDITORIAENUM);

export default LCAUDITORIAENUM;