const LCCARRINHOENUM = {
    TABELA: 'LCCARRINHO',
    LCCARID: 'LCCARID',
    LCCARSENHAID: 'LCCARSENHAID',
    LCCARPRODUTOID: 'LCCARPRODUTOID',
    LCCARQUANTIDADE: 'LCCARQUANTIDADE',
    LCCAREMPRESAID: 'LCCAREMPRESAID',
};

Object.freeze(LCCARRINHOENUM);

export default LCCARRINHOENUM;
