const LCCARRINHOENUM = {
    TABELA: 'LCCARRINHO',
    LCCARID: 'LCCARID',
    LCCARPRODUTOID: 'LCCARPRODUTOID',
    LCCARUSUARIOID: 'LCCARUSUARIOID',
    LCCARQUANTIDADE: 'LCCARQUANTIDADE',
};

Object.freeze(LCCARRINHOENUM);

export default LCCARRINHOENUM;
