const LCVENDAENUM = {
    TABELA: 'LCVENDA',
    LCVENID: 'LCVENID',
    LCVENSENHAID: 'LCVENSENHAID',
    LCVENPRODUTOS: 'LCVENPRODUTOS',
    LCVENDATA: 'LCVENDATA',
};

Object.freeze(LCVENDAENUM);

export default LCVENDAENUM;